# Generated by Django 5.0.1 on 2024-02-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='enppointment_duration_in_minutes',
            field=models.IntegerField(choices=[(30, '30 minutes'), (45, '45 minutes'), (60, '60 minutes'), (75, '75 minutes'), (90, '90 minutes'), (105, '105 minutes'), (120, '120 minutes'), (135, '135 minutes'), (150, '150 minutes'), (165, '165 minutes'), (180, '180 minutes')], default=30),
        ),
    ]
