# Generated by Django 5.0.1 on 2024-02-20 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, height_field=255, max_length=255, null=True, upload_to='user/avatat', width_field=255),
        ),
    ]
