# Generated by Django 5.0.1 on 2024-02-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, height_field='255', max_length=255, null=True, upload_to='user/avatar/', width_field='255'),
        ),
    ]
