# Generated by Django 5.0.1 on 2024-02-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_appointment_message_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='day_of_week',
            field=models.CharField(choices=[('MONDAY', 'Lundi'), ('TUESDAY', 'Mardi'), ('WEDNESDAY', 'Mercredi'), ('THURSDAY', 'Jeudi'), ('FRIDAY', 'Vendredi'), ('SATURDAY', 'Samedi'), ('SUNDAY', 'Dimanche')], max_length=100),
        ),
    ]
